**Importacion de datos**

In [1334]:
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1335]:
df_prueba = pd.read_csv('data/Datos Test Lab 1.csv')
df_completos = pd.read_csv('data/Datos Lab 1.csv')
df_diccionario = pd.read_excel('data/Diccionario de datos.xlsx')

**Limpieza y tratamiento de datos**

*Copia de datos*

In [1336]:
dfc_completos = df_completos.copy()
dfc_prueba = df_prueba.copy()
dfc_diccionario = df_diccionario.copy()

*Revision del estado de la dataset*

In [1337]:
((dfc_completos.isnull().sum()/dfc_completos.shape[0])).sort_values(ascending=False)

temp_max_manana      0.036879
viento_min           0.035326
estacion_anio        0.034161
mes                  0.034161
anio                 0.033385
humedad_max          0.033385
viento_media         0.033385
viento_max           0.031444
humedad_min          0.031056
viento_norte         0.031056
presion_desv         0.031056
rafaga_desv          0.030668
direccion_viento     0.030668
rafaga_media         0.030280
registros_del_dia    0.029891
presion_media        0.029115
presion_min          0.028727
humedad_media        0.028727
rafaga_max           0.028339
rafaga_min           0.027950
viento_desv          0.027950
fecha                0.027950
sector_viento        0.027562
dia_del_anio         0.026398
presion_max          0.024845
viento_este          0.024845
humedad_desv         0.023680
dtype: float64

En este caso todos tienen valores nulos, entonces realizaremos algunos ajustes para poder llenar los datos faltantes

In [1338]:
# Filtrar filas con Calificación nula
nulos = dfc_completos[dfc_completos['temp_max_manana'].isna()].copy()

# Contar cuántas son
print(f"Filas con temp_max_manana nula: {nulos.shape[0]}")

# Guardar los índices
indices = dfc_completos.index[dfc_completos['temp_max_manana'].isna()]

# Mostrar tabla
nulos

Filas con temp_max_manana nula: 95

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento,temp_max_manana
5,2009-01-06,997.0530,NaN,998.49,1.2689,83.774700,67.310000,89.3,4.8864,1.22680,...,0.6808,-0.0178,358.5028,144.0,2009.0,6.0,invierno,January,N,NaN
15,2009-01-16,997.5481,995.15,999.29,1.1148,92.759700,102.543211,81.5,5.2127,1.59950,...,-1.4937,-0.3001,191.3615,144.0,2009.0,16.0,invierno,JUNE,S,NaN
24,2009-01-25,974.0507,971.14,975.36,1.0433,83.009000,59.270000,95.5,10.9192,0.92620,...,-0.7753,0.0561,175.8584,144.0,2009.0,25.0,invierno,January,NaN,NaN
30,2009-01-31,994.3756,989.95,997.42,2.0522,0.884403,73.300000,94.4,5.4441,2.58660,...,1.9530,1.6026,39.3705,144.0,NaN,31.0,Inverano,april,NE,NaN
32,2009-02-02,979.9558,976.36,982.79,2.2236,80.692600,67.710000,91.4,6.7588,1.48330,...,0.5206,0.7330,54.6159,NaN,2009.0,33.0,invierno,February,Noreste,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2379,2015-07-08,983.2930,980.57,986.52,1.6125,61.704600,38.920000,91.9,17.9497,3.04410,...,-1.2799,-2.6516,244.2340,144.0,2015.0,189.0,verano,Nov,SO,NaN
2399,2015-07-28,980.1865,978.56,982.47,0.9953,NaN,38.360000,92.1,19.1092,9.32832,...,-1.3169,-2.0981,237.8845,144.0,2015.0,209.0,invierno,April,so,NaN
2520,2015-11-26,987.5980,980.69,994.68,4.6765,87.659700,72.100000,94.2,6.1423,0.82520,...,NaN,-0.3349,235.0359,144.0,2015.0,330.0,otono,NOVEMBER,SO,NaN
2535,2015-12-11,997.2485,993.42,1001.34,1.9392,0.797528,71.300000,86.0,4.2005,4.71610,...,-4.0667,-2.1221,207.5570,144.0,2015.0,345.0,NaN,December,SOUTHWEST,NaN
2543,2015-12-19,996.6872,996.00,997.76,0.4748,91.381900,73.900000,99.2,7.0292,1.39300,...,-1.1547,-0.2968,194.4167,144.0,2015.0,353.0,invierno,September,Sur,NaN

Como nos damos cuenta en este caso son bastantes las filas afectadas, para ellos realizaremos un ajuste con Pandas para no perder informacion, en este caso pondremos la Moda para llenar aquellos valores nulos en cuanto a los valores numericos.

In [1339]:
moda = dfc_completos['temp_max_manana'].mode().iloc[0]
dfc_completos['temp_max_manana'] = dfc_completos['temp_max_manana'].fillna(moda)

Verificamos si temp_max_manana sigue con valores nulos:

In [1340]:
((dfc_completos.isnull().sum()/dfc_completos.shape[0])).sort_values(ascending=False)

viento_min           0.035326
mes                  0.034161
estacion_anio        0.034161
humedad_max          0.033385
anio                 0.033385
viento_media         0.033385
viento_max           0.031444
humedad_min          0.031056
presion_desv         0.031056
viento_norte         0.031056
direccion_viento     0.030668
rafaga_desv          0.030668
rafaga_media         0.030280
registros_del_dia    0.029891
presion_media        0.029115
presion_min          0.028727
humedad_media        0.028727
rafaga_max           0.028339
fecha                0.027950
viento_desv          0.027950
rafaga_min           0.027950
sector_viento        0.027562
dia_del_anio         0.026398
viento_este          0.024845
presion_max          0.024845
humedad_desv         0.023680
temp_max_manana      0.000000
dtype: float64

Como nos damos cuenta tiene un valor de 0 la variable 'temp_max_manana', ahora procederemos a realizar el mismo ajuste con las demas variables:

In [1341]:
lista_variables  = dfc_completos.columns.tolist()
for variable in lista_variables:
    moda = dfc_completos[variable].mode().iloc[0]
    dfc_completos[variable] = dfc_completos[variable].fillna(moda)

#Verificamos que sea 0 el valor para cada variable
((dfc_completos.isnull().sum()/dfc_completos.shape[0])).sort_values(ascending=False)

fecha                0.0
presion_media        0.0
presion_min          0.0
presion_max          0.0
presion_desv         0.0
humedad_media        0.0
humedad_min          0.0
humedad_max          0.0
humedad_desv         0.0
viento_media         0.0
viento_min           0.0
viento_max           0.0
viento_desv          0.0
rafaga_media         0.0
rafaga_min           0.0
rafaga_max           0.0
rafaga_desv          0.0
viento_norte         0.0
viento_este          0.0
direccion_viento     0.0
registros_del_dia    0.0
anio                 0.0
dia_del_anio         0.0
estacion_anio        0.0
mes                  0.0
sector_viento        0.0
temp_max_manana      0.0
dtype: float64

Verificamos duplicados:

In [1342]:
n_duplicados = int(dfc_completos.duplicated(keep=False).sum())
print(f"Número de registros duplicados: {n_duplicados}")

Número de registros duplicados: 8

Ahora verificamos el dataset de Test

In [1343]:
((dfc_prueba.isnull().sum()/dfc_prueba.shape[0])).sort_values(ascending=False)

fecha                0.0
presion_media        0.0
presion_min          0.0
presion_max          0.0
presion_desv         0.0
humedad_media        0.0
humedad_min          0.0
humedad_max          0.0
humedad_desv         0.0
viento_media         0.0
viento_min           0.0
viento_max           0.0
viento_desv          0.0
rafaga_media         0.0
rafaga_min           0.0
rafaga_max           0.0
rafaga_desv          0.0
viento_norte         0.0
viento_este          0.0
direccion_viento     0.0
registros_del_dia    0.0
anio                 0.0
dia_del_anio         0.0
estacion_anio        0.0
mes                  0.0
sector_viento        0.0
dtype: float64

Como nos damos cuenta, este dataset tiene todos los datos completos

Ahora vamos a revisar la Unicidad de los datos, para esto miraremos si hay registros repetidos. Tambien volveremos las columnas en minusculas, pues en algunos vemos como la columna 'estacion' puede tener valores como 'primavera' o 'PRIMAVERA'.

In [1344]:
#Ponemos los valores de texto en minuscula y quitaremos los espacios o caracteres que no se ven.
columnas_texto = dfc_completos.select_dtypes(include=['object', 'string']).columns
for col in columnas_texto:
    dfc_completos[col] = dfc_completos[col].str.lower().str.strip()
    dfc_prueba[col] = dfc_prueba[col].str.lower().str.strip()


n_duplicados = int(dfc_completos.duplicated(keep=False).sum())
print(f"Número de registros duplicados: {n_duplicados}")

Número de registros duplicados: 8

Borraremos las duplicadas

In [1345]:
dfc_completos.drop_duplicates(keep='last', inplace=True)
n_duplicados = int(dfc_completos.duplicated(keep=False).sum())
print(f"Número de registros duplicados: {n_duplicados}")

Número de registros duplicados: 0

Una vez eliminamos los registros duplicados, vamos a revisar si hay dias que se repitan, esto no tendria sentido.

In [1346]:
dup_counts = (dfc_completos[['fecha']].groupby('fecha').size().reset_index(name='Count').sort_values(by='Count', ascending=False))
dup_counts= dup_counts[dup_counts['Count']>1]

for id_, n in dup_counts[["fecha","Count"]].values:    
    print(f"Id={id_} → {n} apariciones")

Id=2009-01-22 → 73 apariciones
Id=2015-12-07 → 2 apariciones
Id=2010-10-25 → 2 apariciones
Id=2010-08-14 → 2 apariciones
Id=2009-12-08 → 2 apariciones
Id=2009-05-02 → 2 apariciones
Id=2009-03-05 → 2 apariciones
Id=2012-10-04 → 2 apariciones
Id=2012-10-06 → 2 apariciones
Id=2012-11-22 → 2 apariciones
Id=2013-01-02 → 2 apariciones
Id=2013-05-29 → 2 apariciones
Id=2015-01-07 → 2 apariciones
Id=2015-02-03 → 2 apariciones
Id=2015-05-11 → 2 apariciones

Como nos damos cuenta hay dias que se repiten lo cual no tiene sentido dentro de este contexto. Vamos a revisar como se ven estos duplicados.

In [1347]:
dup_table = (
    dfc_completos[dfc_completos['fecha'].duplicated(keep=False)]
    .copy()
    .assign(repeticiones=dfc_completos.groupby('fecha')['fecha'].transform('size'))
    .sort_values(['repeticiones', 'fecha'], ascending=[False, True])
)

dup_table

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento,temp_max_manana,repeticiones
85,2009-01-22,973.3820,971.76,975.24,1.0043,77.666900,59.8600,89.0,7.3810,3.6303,...,-2.1815,218.6516,144.0,2009.0,86.0,primavera,march,so,8.970000,73
96,2009-01-22,984.4544,982.66,985.84,0.8370,71.945300,34.6400,98.2,22.1588,5.7186,...,-0.2385,205.4264,144.0,2009.0,97.0,primavera,january,so,17.420000,73
224,2009-01-22,988.7032,987.59,990.24,0.6328,71.057200,47.7500,95.9,16.3577,1.6595,...,-1.3504,269.9310,144.0,2009.0,225.0,verano,august,o,22.050000,73
237,2009-01-22,989.2619,986.16,990.44,1.1311,78.713500,62.2500,91.4,7.4702,1.4394,...,0.0946,169.6097,144.0,2009.0,238.0,verano,february,s,27.470000,73
266,2009-01-22,996.1611,995.20,997.71,0.6025,88.620800,76.8000,97.6,7.1956,1.1329,...,-0.3574,259.3584,144.0,2009.0,267.0,otono,september,o,15.360000,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2572,2015-02-03,975.4255,972.47,979.12,1.9880,77.969500,64.3600,92.1,7.2394,2.1142,...,-1.5389,230.2684,144.0,2015.0,34.0,verano,june,so,0.205318,2
2321,2015-05-11,998.0015,994.46,1001.51,2.6653,0.564682,0.3256,90.6,19.7073,7.5420,...,-0.0194,180.5918,144.0,2015.0,131.0,primaveraa,aug,s,27.730000,2
2571,2015-05-11,998.0015,994.46,1001.51,2.6653,1.167107,0.3256,90.6,19.7073,7.5420,...,-0.0194,180.5918,144.0,2015.0,131.0,primaveraa,aug,s,27.730000,2
2531,2015-12-07,1004.9268,1001.52,1007.09,1.6678,0.800981,0.6834,100.0,6.1985,2.1028,...,-0.3209,197.1000,144.0,2015.0,341.0,verano,september,so,10.530000,2
2564,2015-12-07,1004.9268,1001.52,1007.09,1.6678,0.800981,0.6834,94.8,6.1985,2.1028,...,-0.3209,197.1000,144.0,2015.0,341.0,verano,september,s,10.530000,2

Nos damos cuenta que no tiene sentido que se repitan los dias, ademas, algunas columnas de estos mismos registros repetidos no tiene sentido, como veremos a continuacion:

In [1348]:
dfc_completos[dfc_completos['fecha']=='2009-01-22']

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento,temp_max_manana
85,2009-01-22,973.3820,971.76,975.24,1.0043,77.666900,59.8600,89.0,7.3810,3.630300,...,-2.7277,-2.1815,218.6516,144.0,2009.0,86.0,primavera,march,so,8.97
96,2009-01-22,984.4544,982.66,985.84,0.8370,71.945300,34.6400,98.2,22.1588,5.718600,...,-0.5018,-0.2385,205.4264,144.0,2009.0,97.0,primavera,january,so,17.42
224,2009-01-22,988.7032,987.59,990.24,0.6328,71.057200,47.7500,95.9,16.3577,1.659500,...,-0.5040,-1.3504,269.9310,144.0,2009.0,225.0,verano,august,o,22.05
237,2009-01-22,989.2619,986.16,990.44,1.1311,78.713500,62.2500,91.4,7.4702,1.439400,...,-0.5158,0.0946,169.6097,144.0,2009.0,238.0,verano,february,s,27.47
266,2009-01-22,996.1611,995.20,997.71,0.6025,88.620800,76.8000,97.6,7.1956,1.132900,...,-0.0672,-0.3574,259.3584,144.0,2009.0,267.0,otono,september,o,15.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2434,2009-01-22,983.5712,980.65,989.33,2.4154,70.488800,44.4100,84.7,13.7964,1.543600,...,-0.7062,-0.7043,224.9255,144.0,2015.0,244.0,otono,september,so,20.03
2464,2009-01-22,1004.4446,1002.62,1006.43,1.2320,0.006877,0.4476,94.2,17.3187,1.892400,...,1.0049,1.3243,52.8086,144.0,2015.0,274.0,otoño,october,ne,17.35
2529,2009-01-22,1002.1970,999.08,1005.34,2.0512,78.005500,57.3400,93.7,10.8056,10.956240,...,-2.8320,-0.6315,192.5714,144.0,2015.0,339.0,summer,january,s,9.80
2563,2009-01-22,9784.1150,971.48,983.54,3.9853,86.731100,69.1100,97.6,9.7926,10.096920,...,-2.7229,-0.1899,183.9897,144.0,2009.0,22.0,verano,octubre,s,5.77
2569,2009-01-22,998.4951,997.15,1000.43,1.1008,0.009583,0.7750,100.0,5.9952,1.963695,...,-0.3106,-0.4228,233.7006,144.0,2013.0,347.0,invernio,december,so,2.87

Para poder arreglar esto, solo podemos dejar el registro con los valores correctos con respecto al dia.

In [1349]:
#Cambiamos el formato de la fecha a datetime
dfc_completos['fecha'] = pd.to_datetime(dfc_completos['fecha'])
dup_table['fecha'] = pd.to_datetime(dup_table['fecha'])

indices_a_eliminar = []


for dato in dfc_completos.itertuples():
    fecha = dato.fecha
    dia_anio = int(dato.dia_del_anio)
    dia_verdadero = fecha.dayofyear
    mes = dato.mes
    mes_fecha = fecha.month_name().lower()
    if not (dia_verdadero == dia_anio and mes_fecha == mes):
        indices_a_eliminar.append(dato.Index)
 
dfc_completos = dfc_completos.drop(index=indices_a_eliminar).reset_index(drop=True)
dfc_completos.drop_duplicates(subset= ['fecha'], keep='last', inplace=True)

Mientras realizabamos la limpieza de las fechas repetidas, nos dimos cuenta que habian fechas que no tenian sentido, pues en la fila los valores internos no eran congruentes uno con los otros, entonces tambien decidimos eliminar esas filas. Ahora verificaremos que este libre de problemas el dataset frente a valores duplicados.

In [1350]:
tabla_dup = int(dfc_completos.duplicated(keep = False).sum())
print('Valores duplicados: ' + str(tabla_dup))

tabla_dup = (
    dfc_completos[dfc_completos['fecha'].duplicated(keep=False)]
    .copy()
    .assign(repeticiones=dfc_completos.groupby('fecha')['fecha'].transform('size'))
    .sort_values(['repeticiones', 'fecha'], ascending=[False, True])
)

tabla_dup

Valores duplicados: 0

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento,temp_max_manana,repeticiones
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1161,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1162,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1163,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1164,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

Como vemos, ya no hay filas duplicadas en ningun caso. Ahora, verificaremos la consistencia de los datos.

In [1351]:
columnas_texto = dfc_completos.select_dtypes(include=['object', 'string']).columns
for col in columnas_texto:
    print(dfc_completos[col].value_counts())

estacion_anio
primavera               274
invierno                233
verano                  215
otono                   213
inverano                 44
estacion_desconocida     41
verano_invierno          39
east                     29
otoño                    11
autumn                   10
primaveraa                8
verno                     8
berano                    7
winter                    7
invernio                  6
spring                    6
fall                      5
primav                    3
summer                    2
Name: count, dtype: int64
mes
may          111
march        106
january      103
july         103
september    101
december      98
august        95
october       94
november      91
february      88
june          87
april         84
Name: count, dtype: int64
sector_viento
so           367
s            242
ne           205
o            140
n             55
e             37
se            26
no            17
suroeste      15
southwest     13
south         10
noreste       10
west           6
sur            5
north          4
northeast      3
east           2
oeste          1
southeast      1
sureste        1
norte          1
Name: count, dtype: int64

Nos damos cuenta que hay multiples valores para algo que deberia de tener solo un valor, vamos a arreglar eso.

In [1352]:
#Primavera
valores_erroneos = ['primav', 'spring', 'primaveraa']
dfc_completos.loc[dfc_completos['estacion_anio'].isin(valores_erroneos), 'estacion_anio'] = 'primavera'

#Verano
valores_erroneos = ['verno', 'verano_invierno', 'berano', 'summer']
dfc_completos.loc[dfc_completos['estacion_anio'].isin(valores_erroneos), 'estacion_anio'] = 'verano'

#otoño
valores_erroneos = ['otono', 'autumn', 'fall']
dfc_completos.loc[dfc_completos['estacion_anio'].isin(valores_erroneos), 'estacion_anio'] = 'otoño'

#Invierno
valores_erroneos = ['inverano', 'winter', 'invernio']
dfc_completos.loc[dfc_completos['estacion_anio'].isin(valores_erroneos), 'estacion_anio'] = 'invierno'

print(dfc_completos['estacion_anio'].value_counts())

estacion_anio
primavera               291
invierno                290
verano                  271
otoño                   239
estacion_desconocida     41
east                     29
Name: count, dtype: int64

Nos damos cuenta que ya quedaron las estaciones bien agrupadas (mas adelante arreglamos las variables con valores inconsistentes). Ahora arreglaremos para cada una de las columnas con textos.

In [1353]:
#sector_viento
#so
valores_erroneos = ['suroeste', 'southwest']
dfc_completos.loc[dfc_completos['sector_viento'].isin(valores_erroneos), 'sector_viento'] = 'so'

#s
valores_erroneos = ['south', 'sur']
dfc_completos.loc[dfc_completos['sector_viento'].isin(valores_erroneos), 'sector_viento'] = 's'

#ne
valores_erroneos = ['noreste', 'northeast']
dfc_completos.loc[dfc_completos['sector_viento'].isin(valores_erroneos), 'sector_viento'] = 'ne'

#o
valores_erroneos = ['west', 'oeste']
dfc_completos.loc[dfc_completos['sector_viento'].isin(valores_erroneos), 'sector_viento'] = 'o'

#n
valores_erroneos = ['north', 'norte']
dfc_completos.loc[dfc_completos['sector_viento'].isin(valores_erroneos), 'sector_viento'] = 'n'

#e
valores_erroneos = ['east']
dfc_completos.loc[dfc_completos['sector_viento'].isin(valores_erroneos), 'sector_viento'] = 'e'

#se
valores_erroneos = ['southeast', 'sureste']
dfc_completos.loc[dfc_completos['sector_viento'].isin(valores_erroneos), 'sector_viento'] = 'se'

for col in columnas_texto:
    print(dfc_completos[col].value_counts())

estacion_anio
primavera               291
invierno                290
verano                  271
otoño                   239
estacion_desconocida     41
east                     29
Name: count, dtype: int64
mes
may          111
march        106
january      103
july         103
september    101
december      98
august        95
october       94
november      91
february      88
june          87
april         84
Name: count, dtype: int64
sector_viento
so    395
s     257
ne    218
o     147
n      60
e      39
se     28
no     17
Name: count, dtype: int64

Ahora nos damos cuenta que ya quedaron todas las columnas de textos corregidas. Ahora miraremos la Validez de los datos.

In [1354]:
dfc_completos.describe()

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,rafaga_min,rafaga_max,rafaga_desv,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,temp_max_manana
count,1161,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000
mean,2012-06-18 07:09:08.837209,996.159503,987.014041,991.697623,1.684674,50.368592,45.103176,90.554565,10.427814,2.277067,...,1.304179,6.932757,1.041514,-0.633769,-0.459668,166.568381,144.006891,2011.904393,181.510767,12.952839
min,2009-01-01 00:00:00,955.510200,944.580000,952.780000,0.226900,0.005912,0.241800,30.830000,0.000000,0.493300,...,0.000000,0.149129,-154.575000,-6.797700,-3.718500,0.394100,90.000000,2009.000000,1.000000,-12.470000
25%,2010-09-20 00:00:00,983.972100,981.680000,987.200000,0.832100,0.838588,0.939000,88.600000,5.777600,1.507100,...,0.440000,4.877762,1.124100,-1.604900,-1.344400,62.445600,144.000000,2010.000000,90.000000,6.080000
50%,2012-06-04 00:00:00,989.420800,987.520000,991.810000,1.402700,67.501200,50.280000,93.500000,10.213500,1.962400,...,0.640000,6.730000,1.513900,-0.533800,-0.437000,197.534200,144.000000,2012.000000,182.000000,13.580000
75%,2014-03-23 00:00:00,994.154400,992.490000,996.620000,2.205500,79.898300,68.840000,96.600000,14.739200,2.632600,...,1.120000,8.650000,2.049900,0.204400,0.277700,224.604900,144.000000,2014.000000,271.000000,19.900000
max,2015-12-29 00:00:00,9928.772000,1010.996120,1012.840000,10.134300,100.000000,102.537565,100.000000,26.341600,24.054480,...,18.916907,18.780000,5.217400,4.809900,3.374000,359.796700,249.000000,2015.000000,365.000000,37.010000
std,NaN,262.542812,8.461296,7.543879,1.195347,36.611979,30.429356,10.538002,5.601482,1.488181,...,2.321500,3.139982,7.828413,1.509698,1.118976,89.556766,3.670472,1.996632,105.902224,9.080353

Vemos columnas con rangos numericos desajustados. Por ejemplo en humedad_min llega a un valor de 102% lo cual no hace sentido, entonces se tiene que arreglar eso.

In [1355]:
dfc_completos.loc[(dfc_completos['humedad_min'] > 100), 'humedad_min'] = None
dfc_completos['humedad_min'] = dfc_completos['humedad_min'].fillna(100)
dfc_completos.describe()

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,rafaga_min,rafaga_max,rafaga_desv,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,temp_max_manana
count,1161,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000
mean,2012-06-18 07:09:08.837209,996.159503,987.014041,991.697623,1.684674,50.368592,45.096274,90.554565,10.427814,2.277067,...,1.304179,6.932757,1.041514,-0.633769,-0.459668,166.568381,144.006891,2011.904393,181.510767,12.952839
min,2009-01-01 00:00:00,955.510200,944.580000,952.780000,0.226900,0.005912,0.241800,30.830000,0.000000,0.493300,...,0.000000,0.149129,-154.575000,-6.797700,-3.718500,0.394100,90.000000,2009.000000,1.000000,-12.470000
25%,2010-09-20 00:00:00,983.972100,981.680000,987.200000,0.832100,0.838588,0.939000,88.600000,5.777600,1.507100,...,0.440000,4.877762,1.124100,-1.604900,-1.344400,62.445600,144.000000,2010.000000,90.000000,6.080000
50%,2012-06-04 00:00:00,989.420800,987.520000,991.810000,1.402700,67.501200,50.280000,93.500000,10.213500,1.962400,...,0.640000,6.730000,1.513900,-0.533800,-0.437000,197.534200,144.000000,2012.000000,182.000000,13.580000
75%,2014-03-23 00:00:00,994.154400,992.490000,996.620000,2.205500,79.898300,68.840000,96.600000,14.739200,2.632600,...,1.120000,8.650000,2.049900,0.204400,0.277700,224.604900,144.000000,2014.000000,271.000000,19.900000
max,2015-12-29 00:00:00,9928.772000,1010.996120,1012.840000,10.134300,100.000000,100.000000,100.000000,26.341600,24.054480,...,18.916907,18.780000,5.217400,4.809900,3.374000,359.796700,249.000000,2015.000000,365.000000,37.010000
std,NaN,262.542812,8.461296,7.543879,1.195347,36.611979,30.416729,10.538002,5.601482,1.488181,...,2.321500,3.139982,7.828413,1.509698,1.118976,89.556766,3.670472,1.996632,105.902224,9.080353

Como vemos ya arreglamos el error en esa columna, ahora arreglaremos los otros valores incosistentes.

In [1356]:
#Presion_media, en este caso vemos como su max tiene un valor mucho mas alto que los demas.
dfc_completos.loc[(dfc_completos['presion_media'] > 1000), 'presion_media'] = None
dfc_completos['presion_media'] = dfc_completos['presion_media'].fillna(dfc_completos['presion_media'].median())


#Arreglamos valores de vientos
vientos = ['viento_media', 'viento_min', 'viento_max', 'viento_desv']

for viento in vientos:
    dfc_completos.loc[(dfc_completos[viento]) < 0 | (dfc_completos[viento] > 30), viento] = None
    dfc_completos[viento] = dfc_completos[viento].fillna(dfc_completos[viento].median())

#Arreglamos el minimo de rafaga_desv
dfc_completos.loc[(dfc_completos['rafaga_desv'] < 0), 'rafaga_desv'] = None
dfc_completos['rafaga_desv'] = dfc_completos['rafaga_desv'].fillna(0)

#Arreglamos los vientos norte y sur, volviendo el absoluto sus valores
dfc_completos['viento_norte'] = dfc_completos['viento_norte'].abs()
dfc_completos['viento_este'] = dfc_completos['viento_este'].abs() 

#Arreglamos registros_del_dia
dfc_completos.loc[(dfc_completos['registros_del_dia'] != 144), 'registros_del_dia'] = None
dfc_completos['registros_del_dia'] = dfc_completos['registros_del_dia'].fillna(144)

dfc_completos.describe()

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,rafaga_min,rafaga_max,rafaga_desv,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,temp_max_manana
count,1161,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.0,1161.000000,1161.000000,1161.000000
mean,2012-06-18 07:09:08.837209,987.374842,987.014041,991.697623,1.684674,50.368592,45.096274,90.554565,10.427814,2.277067,...,1.304179,6.932757,1.639064,1.278562,0.970670,166.568381,144.0,2011.904393,181.510767,12.952839
min,2009-01-01 00:00:00,955.510200,944.580000,952.780000,0.226900,0.005912,0.241800,30.830000,0.000000,0.493300,...,0.000000,0.149129,0.000000,0.000200,0.000700,0.394100,144.0,2009.000000,1.000000,-12.470000
25%,2010-09-20 00:00:00,983.972100,981.680000,987.200000,0.832100,0.838588,0.939000,88.600000,5.777600,1.507100,...,0.440000,4.877762,1.124100,0.504000,0.368900,62.445600,144.0,2010.000000,90.000000,6.080000
50%,2012-06-04 00:00:00,988.633050,987.520000,991.810000,1.402700,67.501200,50.280000,93.500000,10.213500,1.962400,...,0.640000,6.730000,1.513900,1.026500,0.843600,197.534200,144.0,2012.000000,182.000000,13.580000
75%,2014-03-23 00:00:00,992.750800,992.490000,996.620000,2.205500,79.898300,68.840000,96.600000,14.739200,2.632600,...,1.120000,8.650000,2.049900,1.906800,1.484100,224.604900,144.0,2014.000000,271.000000,19.900000
max,2015-12-29 00:00:00,999.986200,1010.996120,1012.840000,10.134300,100.000000,100.000000,100.000000,26.341600,24.054480,...,18.916907,18.780000,5.217400,6.797700,3.718500,359.796700,144.0,2015.000000,365.000000,37.010000
std,NaN,8.097676,8.461296,7.543879,1.195347,36.611979,30.416729,10.538002,5.601482,1.488181,...,2.321500,3.139982,0.728844,1.022285,0.721506,89.556766,0.0,1.996632,105.902224,9.080353

Como previamente habiamos visto, en las estaciones del anio hay unos valores que no tienen sentido, vamos a llenarlos.

In [1357]:
for dato in dfc_completos.itertuples():
    dia = int(dato.dia_del_anio)
    estacion = dato.estacion_anio
    if(estacion == 'estacion_desconocida' or estacion == 'east'):
        #Calculo de estacion
        if(dia > 80 and dia <= 173):
            estacion_real = 'primavera'
        elif(dia > 173 and dia <= 266):
            estacion_real = 'verano'
        elif(dia > 266 and dia <= 356):
            estacion_real = 'otoño'
        else:
            estacion_real = 'invierno'

        dfc_completos.at[dato.Index, 'estacion_anio'] = estacion_real

print(dfc_completos['estacion_anio'].value_counts())

estacion_anio
primavera    309
invierno     305
verano       291
otoño        256
Name: count, dtype: int64

Ahora ya arreglamos el ultimo detalle de los datos que nos hacia falta para que estos tengan consistencia.

**Ingenieria de caracteristicas**

Ahora para poder ver que variables son buenas para escalar miraremos los valores de cada una de ellas.

In [1358]:
dfc_completos.describe()

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,rafaga_min,rafaga_max,rafaga_desv,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,temp_max_manana
count,1161,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.0,1161.000000,1161.000000,1161.000000
mean,2012-06-18 07:09:08.837209,987.374842,987.014041,991.697623,1.684674,50.368592,45.096274,90.554565,10.427814,2.277067,...,1.304179,6.932757,1.639064,1.278562,0.970670,166.568381,144.0,2011.904393,181.510767,12.952839
min,2009-01-01 00:00:00,955.510200,944.580000,952.780000,0.226900,0.005912,0.241800,30.830000,0.000000,0.493300,...,0.000000,0.149129,0.000000,0.000200,0.000700,0.394100,144.0,2009.000000,1.000000,-12.470000
25%,2010-09-20 00:00:00,983.972100,981.680000,987.200000,0.832100,0.838588,0.939000,88.600000,5.777600,1.507100,...,0.440000,4.877762,1.124100,0.504000,0.368900,62.445600,144.0,2010.000000,90.000000,6.080000
50%,2012-06-04 00:00:00,988.633050,987.520000,991.810000,1.402700,67.501200,50.280000,93.500000,10.213500,1.962400,...,0.640000,6.730000,1.513900,1.026500,0.843600,197.534200,144.0,2012.000000,182.000000,13.580000
75%,2014-03-23 00:00:00,992.750800,992.490000,996.620000,2.205500,79.898300,68.840000,96.600000,14.739200,2.632600,...,1.120000,8.650000,2.049900,1.906800,1.484100,224.604900,144.0,2014.000000,271.000000,19.900000
max,2015-12-29 00:00:00,999.986200,1010.996120,1012.840000,10.134300,100.000000,100.000000,100.000000,26.341600,24.054480,...,18.916907,18.780000,5.217400,6.797700,3.718500,359.796700,144.0,2015.000000,365.000000,37.010000
std,NaN,8.097676,8.461296,7.543879,1.195347,36.611979,30.416729,10.538002,5.601482,1.488181,...,2.321500,3.139982,0.728844,1.022285,0.721506,89.556766,0.0,1.996632,105.902224,9.080353

Normalizaremos algunas variables que podrian generar un desbalance en los pesos. Por otro lado, quitaremos la fecha, pues esta variable esta desglosada en otras variables, como lo es mes o dia del anio. Por otro lado, sacaremos de dfc_completo la columna de temp_max_manana, pues esta es la variable objetivo y de no sacarla generariamos un data leakage, aunque este ajuste se hara mas adelante en la separacion de variables.

In [1359]:
from sklearn.preprocessing import MinMaxScaler

dfc_transf = dfc_completos.copy()
dfc_transf.drop(columns=['fecha', 'registros_del_dia'], inplace=True)


scaler = MinMaxScaler()

columnas_a_escalar = [
    'presion_media', 'presion_min', 'presion_max', 'presion_desv',
    'humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv',
    'viento_media', 'viento_min', 'viento_max', 'viento_desv',
    'rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv',
    'viento_norte', 'viento_este', 'direccion_viento', 'dia_del_anio', 'anio', 'temp_max_manana'
]

dfc_transf[['temp_max_manana','anio','presion_media', 'presion_min', 'presion_max', 'presion_desv','humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv','viento_media', 'viento_min', 'viento_max', 'viento_desv','rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv','viento_norte', 'viento_este', 'direccion_viento', 'dia_del_anio']] = scaler.fit_transform(dfc_transf[['temp_max_manana', 'anio','presion_media', 'presion_min', 'presion_max', 'presion_desv','humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv','viento_media', 'viento_min', 'viento_max', 'viento_desv','rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv','viento_norte', 'viento_este', 'direccion_viento', 'dia_del_anio']])

dfc_transf[['temp_max_manana','anio', 'presion_media', 'presion_min', 'presion_max', 'presion_desv','humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv','viento_media', 'viento_min', 'viento_max', 'viento_desv','rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv','viento_norte', 'viento_este', 'direccion_viento', 'dia_del_anio']].head()

,temp_max_manana,anio,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,...,viento_max,viento_desv,rafaga_media,rafaga_min,rafaga_max,rafaga_desv,viento_norte,viento_este,direccion_viento,dia_del_anio
0,0.209175,0.0,0.981100,0.781738,0.800699,0.118336,0.009050,0.006347,0.924823,0.067004,...,0.046040,0.001518,0.044140,0.013216,0.113062,0.162686,0.053196,0.005810,0.509559,0.000000
1,0.239289,0.0,0.967677,0.729793,0.827672,0.293064,0.764567,0.482649,0.911811,0.576260,...,0.107451,0.002188,0.109223,0.020088,0.253926,0.178825,0.102847,0.141508,0.602660,0.005495
2,0.222918,0.0,0.741984,0.610394,0.668498,0.211498,0.894168,0.979417,1.000000,0.170468,...,0.072453,0.002068,0.251348,0.072951,0.229793,0.226837,0.165737,0.279897,0.618659,0.008242
3,0.032134,0.0,0.784592,0.646530,0.745255,0.404203,0.862596,0.745384,0.901691,0.204703,...,0.230547,0.007489,0.476418,0.112598,0.575973,0.174896,0.386510,0.077115,0.016271,0.010989
4,0.239895,0.0,0.934050,0.646530,0.761072,0.105174,0.837737,0.672308,0.845309,0.185501,...,0.062731,0.001764,0.112312,0.026431,0.142078,0.168015,0.100125,0.004599,0.996400,0.013736

Como nos podemos dar cuenta ya tenemos las variables escaladas, ahora realizaremos el mismo proceso para el conjunto de pruebas.

In [1360]:
dfcp_transf = dfc_prueba.copy()
dfcp_transf.drop(columns=['registros_del_dia'], inplace=True)
dfcp_transf[['anio','presion_media', 'presion_min', 'presion_max', 'presion_desv','humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv','viento_media', 'viento_min', 'viento_max', 'viento_desv','rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv','viento_norte', 'viento_este', 'direccion_viento', 'dia_del_anio']] = scaler.fit_transform(dfcp_transf[['anio','presion_media', 'presion_min', 'presion_max', 'presion_desv','humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv','viento_media', 'viento_min', 'viento_max', 'viento_desv','rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv','viento_norte', 'viento_este', 'direccion_viento', 'dia_del_anio']])

dfcp_transf[['anio','presion_media', 'presion_min', 'presion_max', 'presion_desv','humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv','viento_media', 'viento_min', 'viento_max', 'viento_desv','rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv','viento_norte', 'viento_este', 'direccion_viento', 'dia_del_anio']].head()

,anio,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,viento_max,viento_desv,rafaga_media,rafaga_min,rafaga_max,rafaga_desv,viento_norte,viento_este,direccion_viento,dia_del_anio
0,0.0,0.709245,0.698952,0.680598,0.106700,0.959365,0.935897,0.962187,0.048718,0.052274,...,0.154280,0.089115,0.059525,0.030257,0.157633,0.116317,0.506011,0.510651,0.478184,0.000000
1,0.0,0.562389,0.585110,0.570377,0.212209,0.888411,0.866221,0.906923,0.077965,0.215326,...,0.237065,0.291609,0.174039,0.048411,0.168695,0.260608,0.687341,0.591920,0.072845,0.002740
2,0.0,0.418660,0.311348,0.437852,0.546910,0.726723,0.700390,0.845841,0.272429,0.296652,...,0.279398,0.182050,0.289878,0.163389,0.230642,0.231522,0.509779,0.675855,0.331733,0.005479
3,0.0,0.112239,0.174015,0.105024,0.207409,0.761279,0.722687,0.819663,0.219477,0.231986,...,0.241769,0.196990,0.239330,0.042360,0.217367,0.286747,0.432609,0.596603,0.429744,0.008219
4,0.0,0.146516,0.198048,0.080771,0.177444,0.926033,0.952620,0.906923,0.022818,0.191339,...,0.161806,0.115063,0.137614,0.090772,0.115597,0.084867,0.737472,0.597859,0.051020,0.010959

Ahora procederemos a escalar las variables de texto. Para cada una usaremos tecnicas distintas. En el caso de estacion_anio, vamos a eliminar esa columna y crear 3 columnas representando las estaciones del anio, en este le daremos drop_first=True, pues esto es mejor en modelos de Regresion Lineal. En el caso de mes vamos a crear valores entre 0 y 1, siendo estos los valores del mes que son cada uno. Se aplicara la misma tecnica para direccion de vientos, para asi evitar poner muchas mas variables.

In [1361]:
#Estacion anio
#Dataset completo
one_hot_c = pd.get_dummies(dfc_transf['estacion_anio'], drop_first = True ,dtype=int)
dfc_transf = pd.concat([dfc_transf, one_hot_c], axis=1)
dfc_transf = dfc_transf.drop(columns=['estacion_anio'])

#Dataset prueba
one_hot_p = pd.get_dummies(dfcp_transf['estacion_anio'], drop_first = True ,dtype=int)
dfcp_transf = pd.concat([dfcp_transf, one_hot_p], axis=1)
dfcp_transf = dfcp_transf.drop(columns=['estacion_anio'])

#Mes
#Dataset completo
dfc_transf['mes'] = dfc_transf['mes'].map({'january': 1, 'february': 2, 'march': 3, 'april': 4, 'may': 5,
                                           'june': 6, 'july': 7, 'august': 8, 'september': 9, 'october': 10,
                                            'november': 11, 'december': 12})

#Dataset prueba
dfcp_transf['mes'] = dfcp_transf['mes'].map({'january': 1, 'february': 2, 'march': 3, 'april': 4, 'may': 5,
                                           'june': 6, 'july': 7, 'august': 8, 'september': 9, 'october': 10,
                                            'november': 11, 'december': 12})

#Direccion viento
#Dataset completo
dfc_transf['sector_viento'] = dfc_transf['sector_viento'].map({'n': 1, 'ne': 2, 'e': 3, 'se': 4, 's': 5, 'so': 6, 'o': 7, 'no': 8})

#Dataset prueba
dfcp_transf['sector_viento'] = dfcp_transf['sector_viento'].map({'n': 1, 'ne': 2, 'e': 3, 'se': 4, 's': 5, 'so': 6, 'o': 7, 'no': 8})

dfc_transf.describe()

,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,viento_min,...,viento_este,direccion_viento,anio,dia_del_anio,mes,sector_viento,temp_max_manana,otoño,primavera,verano
count,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000
mean,0.716446,0.638912,0.647979,0.147140,0.503657,0.449632,0.863446,0.395869,0.075708,0.035548,...,0.260899,0.462362,0.484065,0.495909,6.474591,4.776055,0.513800,0.220500,0.266150,0.250646
std,0.182068,0.127398,0.125606,0.120652,0.366141,0.304905,0.152349,0.212648,0.063162,0.085983,...,0.194068,0.249182,0.332772,0.290940,3.451824,1.899132,0.183516,0.414762,0.442134,0.433572
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,0.639938,0.558599,0.573094,0.061086,0.008327,0.006989,0.835189,0.219334,0.043028,0.007835,...,0.099037,0.172652,0.166667,0.244505,3.000000,3.000000,0.374899,0.000000,0.000000,0.000000
50%,0.744735,0.646530,0.649850,0.118679,0.674993,0.501595,0.906029,0.387733,0.062353,0.012371,...,0.226720,0.548522,0.500000,0.497253,7.000000,5.000000,0.526475,0.000000,0.000000,0.000000
75%,0.837319,0.721361,0.729937,0.199709,0.798971,0.687645,0.950846,0.559541,0.090798,0.023093,...,0.398999,0.623843,0.833333,0.741758,9.000000,6.000000,0.654204,0.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,12.000000,8.000000,1.000000,1.000000,1.000000,1.000000

Ya quedaron escaladas las variables de texto, ahora falta normalizar estas variables para evitar problemas.

In [1362]:
#Dataset completo
dfc_transf[['mes', 'sector_viento']] = scaler.fit_transform(dfc_transf[['mes', 'sector_viento']])

#Dataset prueba
dfcp_transf[['mes', 'sector_viento']] = scaler.fit_transform(dfcp_transf[['mes', 'sector_viento']])

dfc_transf.describe()

,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,viento_min,...,viento_este,direccion_viento,anio,dia_del_anio,mes,sector_viento,temp_max_manana,otoño,primavera,verano
count,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000
mean,0.716446,0.638912,0.647979,0.147140,0.503657,0.449632,0.863446,0.395869,0.075708,0.035548,...,0.260899,0.462362,0.484065,0.495909,0.497690,0.539436,0.513800,0.220500,0.266150,0.250646
std,0.182068,0.127398,0.125606,0.120652,0.366141,0.304905,0.152349,0.212648,0.063162,0.085983,...,0.194068,0.249182,0.332772,0.290940,0.313802,0.271305,0.183516,0.414762,0.442134,0.433572
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.639938,0.558599,0.573094,0.061086,0.008327,0.006989,0.835189,0.219334,0.043028,0.007835,...,0.099037,0.172652,0.166667,0.244505,0.181818,0.285714,0.374899,0.000000,0.000000,0.000000
50%,0.744735,0.646530,0.649850,0.118679,0.674993,0.501595,0.906029,0.387733,0.062353,0.012371,...,0.226720,0.548522,0.500000,0.497253,0.545455,0.571429,0.526475,0.000000,0.000000,0.000000
75%,0.837319,0.721361,0.729937,0.199709,0.798971,0.687645,0.950846,0.559541,0.090798,0.023093,...,0.398999,0.623843,0.833333,0.741758,0.727273,0.714286,0.654204,0.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Para terminar, decidimos quitar la variable de anio, pues consideramos que para el modelo no es necesario incluirla, pues no tiene sentido para la prediccion de variables.

In [1363]:
dfc_transf.drop(columns=['anio'], inplace=True)
dfcp_transf.drop(columns=['anio', 'fecha'], inplace=True)


dfc_transf.describe()

,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,viento_min,...,viento_norte,viento_este,direccion_viento,dia_del_anio,mes,sector_viento,temp_max_manana,otoño,primavera,verano
count,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000
mean,0.716446,0.638912,0.647979,0.147140,0.503657,0.449632,0.863446,0.395869,0.075708,0.035548,...,0.188064,0.260899,0.462362,0.495909,0.497690,0.539436,0.513800,0.220500,0.266150,0.250646
std,0.182068,0.127398,0.125606,0.120652,0.366141,0.304905,0.152349,0.212648,0.063162,0.085983,...,0.150391,0.194068,0.249182,0.290940,0.313802,0.271305,0.183516,0.414762,0.442134,0.433572
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.639938,0.558599,0.573094,0.061086,0.008327,0.006989,0.835189,0.219334,0.043028,0.007835,...,0.074115,0.099037,0.172652,0.244505,0.181818,0.285714,0.374899,0.000000,0.000000,0.000000
50%,0.744735,0.646530,0.649850,0.118679,0.674993,0.501595,0.906029,0.387733,0.062353,0.012371,...,0.150982,0.226720,0.548522,0.497253,0.545455,0.571429,0.526475,0.000000,0.000000,0.000000
75%,0.837319,0.721361,0.729937,0.199709,0.798971,0.687645,0.950846,0.559541,0.090798,0.023093,...,0.280485,0.398999,0.623843,0.741758,0.727273,0.714286,0.654204,0.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

**Creacion de Regresion Lineal**

Ya terminamos de corregir los datos, ahora empezaremos a crear el modelo. Ahora realizaremos la separacion de las variables, como queremos predecir el valor de temperatura manana.

In [1364]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

target = 'temp_max_manana'
X = dfc_transf.drop(columns=[target])
y = dfc_transf[target]

X_completo = X.copy()
X_prueba = dfcp_transf.copy()

Verificamos ambos datos.

In [1365]:
X_completo.shape, y.shape

((1161, 25), (1161,))

In [1366]:
y

0       0.209175
1       0.239289
2       0.222918
3       0.032134
4       0.239895
          ...
1160    0.366209
1161    0.400364
1162    0.646120
1163    0.551111
1164    0.406580
Name: temp_max_manana, Length: 1161, dtype: float64

Ahora vamos a crear el modelo con los datos que tenemos.

In [1367]:

Modelo = LinearRegression()
Modelo.fit(X_completo, y)

#Predicciones sobre el modelo
y_completo_pred = Modelo.predict(X_completo)

**MAE**

In [1368]:
mae_train = mean_absolute_error(y, y_completo_pred)
print("MAE train: ", mae_train)

MAE train:  0.09526118846841311

**RMSE**

In [1369]:
mse_train = mean_squared_error(y, y_completo_pred)
rmse_train = np.sqrt(mse_train)
print('RMSE train: ', rmse_train)

RMSE train:  0.12465978498964583

**R^2**

In [1370]:
r2_train = r2_score(y,y_completo_pred)
print('R2 train:', r2_train)

R2 train: 0.5381713327532015

**Validacion del modelo**

In [ ]:
mae_test = mean_absolute_error(/11)