In [86]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

In [87]:
df_prueba = pd.read_csv('data/Datos Test Lab 1.csv')
df_completos = pd.read_csv('data/Datos Lab 1.csv')
df_diccionario = pd.read_excel('data/Diccionario de datos.xlsx')

In [88]:
df_prueba.head()

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,rafaga_desv,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento
0,01.01.2016,998.9860,995.57,1000.60,1.1082,96.1493,90.8,98.7,2.0034,0.9649,...,0.8415,-0.8328,0.0927,173.6501,144,2016,1,invierno,January,S
1,02.01.2016,991.4241,989.27,995.51,1.9413,92.3236,85.8,96.8,2.6562,1.9886,...,1.3604,1.1161,0.6688,30.9301,144,2016,2,invierno,January,NE
2,03.01.2016,984.0232,974.12,989.39,4.5841,83.6056,73.9,94.7,6.9967,2.4992,...,1.2558,-0.7923,1.2638,122.0847,144,2016,3,invierno,January,SE
3,04.01.2016,968.2449,966.52,974.02,1.9034,85.4688,75.5,93.8,5.8148,2.0932,...,1.4544,-1.6217,0.7020,156.5944,144,2016,4,invierno,January,SE
4,05.01.2016,970.0099,967.85,972.90,1.6668,94.3521,92.0,96.8,1.4253,1.8380,...,0.7284,1.6549,0.7109,23.2458,144,2016,5,invierno,January,NE

In [89]:
df_completos.head()

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento,temp_max_manana
0,2009-01-01,999.1456,996.50,1000.87,1.3993,0.910860,0.875000,94.8,1.7650,0.7786,...,-0.3618,-0.0223,183.5308,143.0,2009.0,1.0,invierno,January,S,-2.12
1,2009-01-02,999.6006,997.93,1002.65,1.5039,0.920868,86.600000,96.3,2.7588,1.4195,...,0.4267,0.3689,40.8436,144.0,2009.0,2.0,invierno,JULY,NE,-0.82
2,2009-01-03,998.5486,993.05,1002.49,3.1304,76.458100,48.390000,93.9,15.1796,1.2509,...,-0.6993,-0.5268,216.9916,144.0,2009.0,3.0,invierno,January,SO,-0.63
3,2009-01-04,988.5107,985.12,992.93,2.3223,89.417400,97.946704,NaN,4.4904,1.7204,...,-1.1268,-1.0413,222.7419,144.0,2009.0,4.0,invierno,JANUARY,SO,-1.44
4,2009-01-05,990.4057,NaN,997.54,4.2315,86.260400,74.600000,93.2,5.3922,3.8003,...,2.6275,0.2874,6.2418,NaN,2009.0,5.0,East,January,N,-10.88

In [90]:
#limpieza de datos
df_completos.isnull().mean() *100

fecha                2.795031
presion_media        2.911491
presion_min          2.872671
presion_max          2.484472
presion_desv         3.105590
humedad_media        2.872671
humedad_min          3.105590
humedad_max          3.338509
humedad_desv         2.368012
viento_media         3.338509
viento_min           3.532609
viento_max           3.144410
viento_desv          2.795031
rafaga_media         3.027950
rafaga_min           2.795031
rafaga_max           2.833851
rafaga_desv          3.066770
viento_norte         3.105590
viento_este          2.484472
direccion_viento     3.066770
registros_del_dia    2.989130
anio                 3.338509
dia_del_anio         2.639752
estacion_anio        3.416149
mes                  3.416149
sector_viento        2.756211
temp_max_manana      3.687888
dtype: float64

In [91]:
print(df_completos.shape)
display(df_completos.head())
df_completos.info()

display(pd.DataFrame({
    "Tipo": df_completos.dtypes,
    "Nulos": df_completos.isnull().sum(),
    "% Nulos": df_completos.isnull().mean() * 100,
    "Unicos": df_completos.nunique()
}))

(2576, 27)

,fecha,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,...,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento,temp_max_manana
0,2009-01-01,999.1456,996.50,1000.87,1.3993,0.910860,0.875000,94.8,1.7650,0.7786,...,-0.3618,-0.0223,183.5308,143.0,2009.0,1.0,invierno,January,S,-2.12
1,2009-01-02,999.6006,997.93,1002.65,1.5039,0.920868,86.600000,96.3,2.7588,1.4195,...,0.4267,0.3689,40.8436,144.0,2009.0,2.0,invierno,JULY,NE,-0.82
2,2009-01-03,998.5486,993.05,1002.49,3.1304,76.458100,48.390000,93.9,15.1796,1.2509,...,-0.6993,-0.5268,216.9916,144.0,2009.0,3.0,invierno,January,SO,-0.63
3,2009-01-04,988.5107,985.12,992.93,2.3223,89.417400,97.946704,NaN,4.4904,1.7204,...,-1.1268,-1.0413,222.7419,144.0,2009.0,4.0,invierno,JANUARY,SO,-1.44
4,2009-01-05,990.4057,NaN,997.54,4.2315,86.260400,74.600000,93.2,5.3922,3.8003,...,2.6275,0.2874,6.2418,NaN,2009.0,5.0,East,January,N,-10.88

<class 'pandas.DataFrame'>
RangeIndex: 2576 entries, 0 to 2575
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha              2504 non-null   str
 1   presion_media      2501 non-null   float64
 2   presion_min        2502 non-null   float64
 3   presion_max        2512 non-null   float64
 4   presion_desv       2496 non-null   float64
 5   humedad_media      2502 non-null   float64
 6   humedad_min        2496 non-null   float64
 7   humedad_max        2490 non-null   float64
 8   humedad_desv       2515 non-null   float64
 9   viento_media       2490 non-null   float64
 10  viento_min         2485 non-null   float64
 11  viento_max         2495 non-null   float64
 12  viento_desv        2504 non-null   float64
 13  rafaga_media       2498 non-null   float64
 14  rafaga_min         2504 non-null   float64
 15  rafaga_max         2503 non-null   float64
 16  rafaga_desv        2497 non-null   float64
 17  viento_norte       2496 non-null   float64
 18  viento_este        2512 non-null   float64
 19  direccion_viento   2497 non-null   float64
 20  registros_del_dia  2499 non-null   float64
 21  anio               2490 non-null   float64
 22  dia_del_anio       2508 non-null   float64
 23  estacion_anio      2488 non-null   str
 24  mes                2488 non-null   str
 25  sector_viento      2505 non-null   str
 26  temp_max_manana    2481 non-null   float64
dtypes: float64(23), str(4)
memory usage: 543.5 KB

                      Tipo  Nulos   % Nulos  Unicos
fecha                  str     72  2.795031    2486
presion_media      float64     75  2.911491    2476
presion_min        float64     74  2.872671    1727
presion_max        float64     64  2.484472    1613
presion_desv       float64     80  3.105590    2359
humedad_media      float64     74  2.872671    2474
humedad_min        float64     80  3.105590    1979
humedad_max        float64     86  3.338509     380
humedad_desv       float64     61  2.368012    2480
viento_media       float64     86  3.338509    2416
viento_min         float64     91  3.532609     405
viento_max         float64     81  3.144410    1505
viento_desv        float64     72  2.795031    2325
rafaga_media       float64     78  3.027950    2409
rafaga_min         float64     72  2.795031     292
rafaga_max         float64     73  2.833851    1093
rafaga_desv        float64     79  3.066770    2357
viento_norte       float64     80  3.105590    2412
viento_este        float64     64  2.484472    2423
direccion_viento   float64     79  3.066770    2474
registros_del_dia  float64     77  2.989130       9
anio               float64     86  3.338509       7
dia_del_anio       float64     68  2.639752     366
estacion_anio          str     88  3.416149      28
mes                    str     88  3.416149      61
sector_viento          str     71  2.756211      33
temp_max_manana    float64     95  3.687888    1763

Podemos observar que el porcentaje de datos nulos en cada columna son menores al 4%, por ende voy a proceder a llenar estos espacios con la mediana de el resto, usare la mediana porque no se desplaza por datos atipicos como la media.

In [ ]:
# =========================================================
# 1. ELIMINAR FILAS SIN VARIABLE OBJETIVO
# =========================================================

df_completos = df_completos.dropna(subset=["temp_max_manana"]).copy()


# =========================================================
# 2. CORREGIR Y APROVECHAR LA FECHA
# =========================================================

df_completos["fecha"] = pd.to_datetime(
    df_completos["fecha"],
    errors="coerce"
)

# Eliminar únicamente filas cuya fecha no se pueda interpretar
df_completos = df_completos.dropna(subset=["fecha"])


# =========================================================
# 3. RECONSTRUIR VARIABLES DE FECHA
# =========================================================

# Año correcto
df_completos["anio"] = df_completos["fecha"].dt.year

# Día correcto del año
df_completos["dia_del_anio"] = df_completos["fecha"].dt.dayofyear

# Mes correcto
df_completos["mes"] = (
    df_completos["fecha"]
    .dt.month_name()
    .str.lower()
)

# Estación correcta según el mes
estaciones = {
    12: "invierno",
    1: "invierno",
    2: "invierno",

    3: "primavera",
    4: "primavera",
    5: "primavera",

    6: "verano",
    7: "verano",
    8: "verano",

    9: "otono",
    10: "otono",
    11: "otono"
}

df_completos["estacion_anio"] = (
    df_completos["fecha"].dt.month.map(estaciones)
)


# =========================================================
# 4. CORREGIR HUMEDAD
# =========================================================

columnas_humedad = [
    "humedad_media",
    "humedad_min",
    "humedad_max"
]

for columna in columnas_humedad:

    # Algunos valores están entre 0 y 1 en vez de 0 y 100
    mascara = (
        (df_completos[columna] >= 0) &
        (df_completos[columna] <= 1)
    )

    df_completos.loc[mascara, columna] = (
        df_completos.loc[mascara, columna] * 100
    )

    # Humedades imposibles se convierten en nulos
    df_completos.loc[
        (df_completos[columna] < 0) |
        (df_completos[columna] > 100),
        columna
    ] = float("nan")


# =========================================================
# 5. CORREGIR PRESIÓN
# =========================================================

columnas_presion = [
    "presion_media",
    "presion_min",
    "presion_max"
]

for columna in columnas_presion:

    df_completos.loc[
        (df_completos[columna] < 900) |
        (df_completos[columna] > 1100),
        columna
    ] = float("nan")


# =========================================================
# 6. CORREGIR VARIABLES QUE NO PUEDEN SER NEGATIVAS
# =========================================================

columnas_no_negativas = [
    "presion_desv",
    "humedad_desv",
    "viento_media",
    "viento_min",
    "viento_max",
    "viento_desv",
    "rafaga_media",
    "rafaga_min",
    "rafaga_max",
    "rafaga_desv"
]

for columna in columnas_no_negativas:

    df_completos.loc[
        df_completos[columna] < 0,
        columna
    ] = float("nan")


# =========================================================
# 7. CORREGIR DIRECCIÓN DEL VIENTO
# =========================================================

df_completos.loc[
    (df_completos["direccion_viento"] < 0) |
    (df_completos["direccion_viento"] >= 360),
    "direccion_viento"
] = float("nan")


# =========================================================
# 8. RECONSTRUIR SECTOR DEL VIENTO
# =========================================================

def obtener_sector(angulo):

    if pd.isna(angulo):
        return None

    angulo = angulo % 360

    sectores = [
        "N",
        "NE",
        "E",
        "SE",
        "S",
        "SO",
        "O",
        "NO"
    ]

    indice = int(((angulo + 22.5) // 45) % 8)

    return sectores[indice]


df_completos["sector_viento"] = (
    df_completos["direccion_viento"].apply(obtener_sector)
)

# =========================================================
# 9. NORMALIZAR OTRAS COLUMNAS DE TEXTO
# =========================================================

columnas_texto = df_completos.select_dtypes(
    include=["object", "string"]
).columns

for columna in columnas_texto:

    # Convertir a object para evitar pd.NA
    df_completos[columna] = df_completos[columna].astype("object")

    # Reemplazar valores faltantes por NaN estándar
    df_completos[columna] = df_completos[columna].where(
        df_completos[columna].notna(),
        float("nan")
    )

    # Limpiar espacios y pasar a minúsculas
    df_completos[columna] = (
        df_completos[columna]
        .str.strip()
        .str.lower()
    )


# =========================================================
# 10. ELIMINAR FECHA
# =========================================================

# Ya utilizamos la fecha para obtener mes, año y día del año.
# No la utilizaremos directamente en LinearRegression.

df_completos = df_completos.drop(
    columns=["fecha"],
    errors="ignore"
)


# =========================================================
# 11. VERIFICACIÓN
# =========================================================

print("Dimensiones finales:")
print(df_completos.shape)

print("\nValores nulos restantes:")
print(df_completos.isnull().sum())

print("\nTotal de valores nulos:")
print(df_completos.isnull().sum().sum())

Dimensiones finales:
(2411, 26)

Valores nulos restantes:
presion_media         76
presion_min           68
presion_max           59
presion_desv          78
humedad_media         72
humedad_min           94
humedad_max           78
humedad_desv          59
viento_media          83
viento_min            87
viento_max            75
viento_desv           67
rafaga_media          74
rafaga_min            68
rafaga_max            68
rafaga_desv          319
viento_norte          73
viento_este           57
direccion_viento      73
registros_del_dia     74
anio                   0
dia_del_anio           0
estacion_anio          0
mes                    0
sector_viento         73
temp_max_manana        0
dtype: int64

Total de valores nulos:
1775

In [93]:
df_completos.head()

,presion_media,presion_min,presion_max,presion_desv,humedad_media,humedad_min,humedad_max,humedad_desv,viento_media,viento_min,...,viento_norte,viento_este,direccion_viento,registros_del_dia,anio,dia_del_anio,estacion_anio,mes,sector_viento,temp_max_manana
0,999.1456,996.50,1000.87,1.3993,91.0860,87.500000,94.8,1.7650,0.7786,0.05,...,-0.3618,-0.0223,183.5308,143.0,2009,1,invierno,january,s,-2.12
1,999.6006,997.93,1002.65,1.5039,92.0868,86.600000,96.3,2.7588,1.4195,0.22,...,0.4267,0.3689,40.8436,144.0,2009,2,invierno,january,ne,-0.82
2,998.5486,993.05,1002.49,3.1304,76.4581,48.390000,93.9,15.1796,1.2509,0.12,...,-0.6993,-0.5268,216.9916,144.0,2009,3,invierno,january,so,-0.63
3,988.5107,985.12,992.93,2.3223,89.4174,97.946704,NaN,4.4904,1.7204,0.54,...,-1.1268,-1.0413,222.7419,144.0,2009,4,invierno,january,so,-1.44
4,990.4057,NaN,997.54,4.2315,86.2604,74.600000,93.2,5.3922,3.8003,1.00,...,2.6275,0.2874,6.2418,NaN,2009,5,invierno,january,n,-10.88

Modelo:

In [94]:
X = df_completos.drop(columns=["temp_max_manana"])
y = df_completos["temp_max_manana"]

In [95]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("Entrenamiento:", X_train.shape)
print("Prueba:", X_test.shape)

Entrenamiento: (1808, 25)
Prueba: (603, 25)

In [96]:
columnas_numericas = X_train.select_dtypes(include="number").columns
columnas_categoricas = X_train.select_dtypes(exclude="number").columns

print("Numéricas:")
print(list(columnas_numericas))

print("\nCategóricas:")
print(list(columnas_categoricas))

Numéricas:
['presion_media', 'presion_min', 'presion_max', 'presion_desv', 'humedad_media', 'humedad_min', 'humedad_max', 'humedad_desv', 'viento_media', 'viento_min', 'viento_max', 'viento_desv', 'rafaga_media', 'rafaga_min', 'rafaga_max', 'rafaga_desv', 'viento_norte', 'viento_este', 'direccion_viento', 'registros_del_dia', 'anio', 'dia_del_anio']

Categóricas:
['estacion_anio', 'mes', 'sector_viento']

In [97]:
pipeline_numerico = Pipeline(
    steps=[
        ("imputacion", SimpleImputer(strategy="median"))
    ]
)

pipeline_categorico = Pipeline(
    steps=[
        ("imputacion", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocesador = ColumnTransformer(
    transformers=[
        ("numericas", pipeline_numerico, columnas_numericas),
        ("categoricas", pipeline_categorico, columnas_categoricas)
    ]
)

In [100]:
modelo_1 = Pipeline(
    steps=[
        ("preprocesamiento", preprocesador),
        ("regresion", LinearRegression())
    ]
)

In [101]:
modelo_1.fit(X_train, y_train)

TypeError: boolean value of NA is ambiguous